# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node
   steps:
     - checkout
     - run: npm install
     - run: npm install mocha
     - run: mocha
  # test:
  #   override:    
  #     - mocha 